plugins:
  cakeday_enabled:
    default: true
    client: true
  cakeday_emoji:
    default: 'cake'
    client: true
  cakeday_birthday_celebrate:
    default: true
    client: true
  cakeday_birthday_enabled:
    default: true
    client: true
  cakeday_birthday_emoji:
    default: 'birthday'
    client: true
  cakeday_birthday_show_year:
    default: false
    client: true
  cakeday_birthday_formatdmy:
    default: false
    client: true
  cakeday_birthday_required:
    default: false
    client: true
  cakeday_birthday_allowchange:
    default: true
    client: true
  cakeday_birthday_allowshowage:
    default: true
    client: true
  cakeday_secret_emoji:
    default: 'shushing_face'
    client: true
  cakeday_min_age_controlvisibility:
    default: 18
    client: true
  cakeday_show_age_to_groups:
    default: ""
    client: true
    type: group_list
